services:
  db:
    image: postgres:17-alpine
    container_name: curricuvita_postgres_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: curricuvita
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d curricuvita"]
      interval: 5s
      timeout: 3s
      retries: 10
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: curricuvita_web_app
    ports:
      - "${APP_PORT}:10000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
